//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humraah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string Locality { get; set; }
        public string ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Station Station { get; set; }
    }
}
