//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humraah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambulance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ambulance()
        {
            this.Types = new HashSet<Type>();
        }
    
        public int Id { get; set; }
        public string color { get; set; }
        public long plateNo { get; set; }
        public bool available { get; set; }
        public string StationId { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Types { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
